name: Setup

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and run containers
        run: docker compose up -d --build web postgres

      - name: Wait for server
        run: |
          for i in {1..15}; do
            if curl -s http://127.0.0.1:8080/ > /dev/null; then
              echo "Flask is up"
              exit 0
            fi
            sleep 2
          done
          echo "Flask did not start"
          exit 1

      - name: Run client
        run: docker compose run --rm client

      - name: Run tests
        run: docker compose exec -T web env PYTHONPATH=/app pytest tests/unit_tests.py

      - name: Stop containers
        run: docker compose down