name: Setup
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t postgres:latest .
      - name: Run container, create database
        run: |
          docker run -d --name notebook-postgres \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=password \
            -e POSTGRES_DB=notebook \
            -p 5432:5432 \
            my-notebook-postgres:latest
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8080/; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 2
            fi
          done